# Generated by Django 6.0.6 on 2026-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bulbs', 'Bulbs'), ('Plugs', 'Plugs'), ('Switches', 'Switches'), ('Wires', 'Wires'), ('Fans', 'Fans'), ('MCB', 'MCB'), ('Sockets', 'Sockets'), ('Holders', 'Holders')], default='bulbs', max_length=50),
        ),
    ]
